### ISSUE TITLE
子命令错误的调用方式导致panic

### ISSUE THREAD

**Issue by Greyh4t** [guonaihong/clop#86]
以下代码调用的时候如果子命令前面有-，会panic，如 `cloptest.exe -server`
```go
package main

import "github.com/guonaihong/clop"

type Args struct {
	Server Server `clop:"subcommand=server" usage:"Run in server model"`
}

type Server struct {
}

func main() {
	var args Args
	clop.Bind(&args)
}
```

报错信息
```cmd
D:\cloptest> cloptest.exe -server
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/antlabs/strsim.findBestMatch({0xc0000120b1, 0x6}, {0xae4110, 0x0, 0xae4101?}, {0x0, 0x0, 0x0})
        C:/gopkg/pkg/mod/github.com/antlabs/strsim@v0.0.2/strsim_priv.go:46 +0x165
github.com/antlabs/strsim.FindBestMatchOne(...)
        C:/gopkg/pkg/mod/github.com/antlabs/strsim@v0.0.2/strsim.go:18
github.com/guonaihong/clop.(*Clop).maybeOpt(0xc000160f00, {0xc0000120b1, 0x6})
        C:/gopkg/pkg/mod/github.com/guonaihong/clop@v0.2.1/maybe_opt.go:17 +0x145
github.com/guonaihong/clop.(*Clop).genMaybeHelpMsg(0x90cea9?, {0xc0000120b1?, 0xc00029fc88?})
        C:/gopkg/pkg/mod/github.com/guonaihong/clop@v0.2.1/maybe_opt.go:26 +0x1e
github.com/guonaihong/clop.(*Clop).unknownOptionErrorShort(0x0?, {0xc00035fc70?, 0xc00035fc70?}, {0xc0000120b1, 0x6})
        C:/gopkg/pkg/mod/github.com/guonaihong/clop@v0.2.1/clop.go:198 +0x95
github.com/guonaihong/clop.(*Clop).parseShort(0xc000160f00, {0xc0000120b1, 0x6}, 0xc00029fe10)
        C:/gopkg/pkg/mod/github.com/guonaihong/clop@v0.2.1/clop.go:403 +0x2cc
github.com/guonaihong/clop.(*Clop).getOptionAndSet(0x0?, {0xc0000120b1?, 0x0?}, 0x0?, 0x1)
        C:/gopkg/pkg/mod/github.com/guonaihong/clop@v0.2.1/clop.go:518 +0xcf
github.com/guonaihong/clop.(*Clop).parseOneOption(0xc000160f00, 0xae4110?)
        C:/gopkg/pkg/mod/github.com/guonaihong/clop@v0.2.1/clop.go:925 +0x40e
github.com/guonaihong/clop.(*Clop).bindStruct(0xc000160f00)
        C:/gopkg/pkg/mod/github.com/guonaihong/clop@v0.2.1/clop.go:944 +0x50
github.com/guonaihong/clop.(*Clop).Bind(0xc000160f00, {0x8b7e00, 0xae4110})
        C:/gopkg/pkg/mod/github.com/guonaihong/clop@v0.2.1/clop.go:968 +0xd6
github.com/guonaihong/clop.Bind(...)
        C:/gopkg/pkg/mod/github.com/guonaihong/clop@v0.2.1/clop.go:1028
main.main()
        D:/cloptest/main.go:14 +0x78
```

**Comment by guonaihong** [comment]
感谢发现. 我等会儿修复下.

**Comment by guonaihong** [comment]
试下v0.2.2版本.

**Comment by Greyh4t** [comment]
> 试下v0.2.2版本. 我这边自测是解决了, 那先关闭issue了.

经测试已修复👍
